apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-mesh-demo

resources:
  - namespace.yaml
  - idp
  - app
  - api
  - sa-binding.yaml

configurations:
  - config.yaml

images:
  - name: provider
    newName: ghcr.io/wirepact/demo-applications/oidc-provider
    newTag: latest
  - name: app
    newName: ghcr.io/wirepact/demo-applications/oidc-app
    newTag: latest
  - name: api
    newName: ghcr.io/wirepact/demo-applications/basic-auth-api
    newTag: latest
