apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-mesh-demo

resources:
  - namespace.yaml
  - keycloak
  - app
  - api

configurations:
  - config.yaml

images:
  - name: keycloak
    newName: quay.io/keycloak/keycloak
    newTag: latest
  - name: app
    newName: ghcr.io/wirepact/k8s-demo-application-app
    newTag: latest
  - name: api
    newName: ghcr.io/wirepact/k8s-demo-application-api
    newTag: latest
