apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      hostAliases:
        - ip: '192.168.65.2'
          hostnames:
            - 'api.localhost'
            - 'app.localhost'
            - 'idp.localhost'
      containers:
        - name: app
          image: app
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 3000
              name: http
