apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app-

commonLabels:
  app.kubernetes.io/part-of: k8s-demo-app
  app.kubernetes.io/component: demo-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mesh-participant.yaml

configMapGenerator:
  - name: config
    literals:
      - OIDC_ISSUER=http://idp.localhost
      - OIDC_CLIENT_ID=wirepact
      - OIDC_CLIENT_SECRET=secret
      - NEXTAUTH_URL=http://app.localhost/
      - API_URL=http://api.localhost/swapi/people
