apiVersion: wirepact.ch/v1alpha1
kind: MeshParticipant
metadata:
  name: participant
spec:
  deployment: deploy
  service: svc
  targetPort: 3000
  translator: token-exchange
  env:
    ISSUER: http://idp.localhost
    CLIENT_ID: wirepact
    CLIENT_SECRET: secret
    AUTH_TYPE: client-credentials
