apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      containers:
        - name: api
          image: api
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: config
