apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: api-

commonLabels:
  app.kubernetes.io/part-of: k8s-demo-app
  app.kubernetes.io/component: demo-api

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
