apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: api-

configurations:
  - config.yaml

commonLabels:
  app.kubernetes.io/part-of: k8s-demo-app
  app.kubernetes.io/component: demo-api

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mesh-participant.yaml

configMapGenerator:
  - name: config
    literals:
      - PORT=8080
      - AUTH_USERNAME=foo
      - AUTH_PASSWORD=bar

secretGenerator:
  - name: credentials
    literals:
      - foo=foo:bar
