apiVersion: wirepact.ch/v1alpha1
kind: MeshParticipant
metadata:
  name: participant
spec:
  deployment: deploy
  targetPort: 8080
  service: svc
  translator: basic-auth
  env:
    K8S_SECRET_NAME: credentials
    MODE: kubernetes
